# Copyright 2018 Cerebro Scholar
# generated by JE KIM
"""
match tags to paper_clean database.
1. rawkey exist => rawkeyToTag matching
2. rawkey not exit => extract rawkey from title&abstract matching => rawkeyToTag matching
    : TODO extract rawkey with RNN.
"""
import pandas as pd
from printUtils import *

def step_matching(rawToTag, keylist, cnt) :
    cnt[0] = cnt[0] + 1
    if cnt[0] % 500 == 0 :
        print('processing : {}th papers'.format(cnt[0]))
    return list(set([list(rawToTag[rawToTag.rawkey == each].tag)[0] for each in keylist]))

def matchTags(rawToTag, papers) :
    print(blue('matching Tags and generating cerebDB..'))
    if 'rawkeys' not in papers.columns :
        print(red('rawkeys column not exist. Please run additional cleansing module.'))
        return
    
    cereb_db = papers.set_index('p_id')
    cereb_db.sort_values('max_cite', ascending=False, inplace=True)

    cnt = [0]
    cereb_db['tags'] = cereb_db[cereb_db['rawkeys'].isna() == False].rawkeys.apply(lambda x: step_matching(rawToTag, x, cnt))

    print(blue('Done. Total {:,} papers, with {:,} papers with tags'.format(len(cereb_db), len(cereb_db[cereb_db.tags.isna()==False]))))
    print(cereb_db[cereb_db.tags.isna() == False].head(10))
    return cereb_db