# Copyright 2018 Cerebro Scholar
# generated by JE KIM
"""modules for pretty printing >_<"""

def red(text) :
    return "\x1b[31m" + text + "\x1b[0m"

def blue(text) :
    return "\x1b[34m" + text + "\x1b[0m"

def yellow(text) :
    return "\x1b[33m" + text + "\x1b[0m"